// <auto-generated />
using CB.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CB.Infrastructure.Migrations
{
    [DbContext(typeof(ContaBancariaContext))]
    [Migration("20180428014156_manyToMany")]
    partial class manyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CB.ApplicationCore.Entity.Conta", b =>
                {
                    b.Property<int>("ContaId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataAbertura");

                    b.Property<int>("Numero");

                    b.Property<bool>("Situacao");

                    b.Property<int?>("TipoContaId");

                    b.HasKey("ContaId");

                    b.HasIndex("TipoContaId");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.ContaPessoa", b =>
                {
                    b.Property<int>("ContaId");

                    b.Property<int>("PessoaId");

                    b.HasKey("ContaId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("ContaPessoa");
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("CEP");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Numero");

                    b.HasKey("EnderecoId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.Movimentacao", b =>
                {
                    b.Property<int>("MovimentacaoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContaId");

                    b.Property<DateTime>("DataMovimentacao");

                    b.Property<decimal>("Valor");

                    b.HasKey("MovimentacaoId");

                    b.HasIndex("ContaId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .HasMaxLength(14);

                    b.Property<string>("Email");

                    b.Property<int>("EnderecoId");

                    b.Property<string>("Nome")
                        .HasMaxLength(40);

                    b.HasKey("PessoaId");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.TipoConta", b =>
                {
                    b.Property<int>("TipoContaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.HasKey("TipoContaId");

                    b.ToTable("TipoContas");
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.Conta", b =>
                {
                    b.HasOne("CB.ApplicationCore.Entity.TipoConta", "TipoConta")
                        .WithMany("Contas")
                        .HasForeignKey("TipoContaId");
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.ContaPessoa", b =>
                {
                    b.HasOne("CB.ApplicationCore.Entity.Conta", "Conta")
                        .WithMany("ContaPessoas")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CB.ApplicationCore.Entity.Pessoa", "Pessoa")
                        .WithMany("ContaPessoas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.Movimentacao", b =>
                {
                    b.HasOne("CB.ApplicationCore.Entity.Conta", "Conta")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ContaId");
                });

            modelBuilder.Entity("CB.ApplicationCore.Entity.Pessoa", b =>
                {
                    b.HasOne("CB.ApplicationCore.Entity.Endereco", "Endereco")
                        .WithOne("Pessoa")
                        .HasForeignKey("CB.ApplicationCore.Entity.Pessoa", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
